### ISSUE TITLE
Support non-rectangular images

### ISSUE THREAD

**Issue by LasseD** [LasseD/svg2ldraw#11]
Use a special color to detect "no color" and crop the image to the shape wanted.

**Comment by cameronmiller1988** [comment]
Hello, Has this been resolved? I have a circular decal (sticker) I would like to show in some instructions and I cannot seem to avoid the box color.

**Comment by LasseD** [comment]
Hi there. Unfortunately there have been no pull requests submitted for this issue yet. If someone has made a solution for it, then I will make the time to review the PR.

**Comment by LasseD** [comment]
Fixed in latest push to master.
