### ISSUE TITLE
Issue with the svg transformation

### ISSUE THREAD

**Issue by urllib2** [LasseD/svg2ldraw#12]
Hi, I want to create a sticker but I upload the svg file it shows errors and the process deletes the text border. I created the file with illustrator and it already takes a long time to be uploaded. Is there any other program to create the svg file?

[roboticslab.io 01.zip](https://github.com/LasseD/svg2ldraw/files/4122254/roboticslab.io.01.zip)

**Comment by LasseD** [comment]
Hi there. I can see that your SVG file has a lot of small details, which cause issues when svg2ldraw tries to convert them to LDraw primitives. You can try with https://github.com/tcobbs/SvgToDat if you want to have an LDraw file without textures.

My recommendation is to use textures - convert your SVG file to PNG and simply use it as a texture on the part that you want it on, or create a sticker for the texture.

**Comment by urllib2** [comment]
I manage to do it, thank you!
